FROM ubuntu:22.04
RUN apt-get -y update
RUN apt-get -y install build-essential
RUN apt-get -y install git
WORKDIR /root
RUN git clone https://github.com/AkyrosXD/unity-tcp-udp-client-server.git
WORKDIR /root/unity-tcp-udp-client-server/server
RUN make clean && make
EXPOSE 5004 5025/udp
CMD ["./server"]